Accept spaces in project name
bashbunni/pjs pull request #21
Opened 2022-06-01 20:22 UTC by nguyen-anthony

Using bufio and os.Stdin to read the entire line instead of using Scanf will allow you to accept spaces in the project name.

2022-06-01 20:25 UTC, nguyen-anthony commented
This is related to [Issue #18](https://github.com/bashbunni/project-management/issues/18)

2022-06-15 20:17 UTC, bashbunni requested changes
Please import "os" and "bufio" in this file so we don't get an error :) will approve once that's done. Thank you so much for the PR!

2022-06-16 06:04 UTC, nguyen-anthony commented
> Please import "os" and "bufio" in this file so we don't get an error :) will approve once that's done. Thank you so much for the PR!

This should be done now. Idk how those imports did not make it through.

2022-06-17 16:28 UTC, bashbunni approved these changes

2022-06-17 17:10 UTC, merged